import subprocess
from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "run_accepted_physical_feature_model_checkpoint.sh"
CONTROLLER = Path(__file__).resolve().parents[1] / "scripts" / "run_accepted_1m_campaign_controller.sh"


def test_checkpoint_runner_shell_and_controller_thread_alias_contract():
    syntax = subprocess.run(["bash", "-n", str(SCRIPT)], capture_output=True, text=True, check=False)
    assert syntax.returncode == 0, syntax.stderr

    help_result = subprocess.run(
        ["bash", str(SCRIPT), "--model-threads", "3", "--help"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert help_result.returncode == 0, help_result.stderr
    assert "physical-cell-held-out tandem tests" in help_result.stdout


def test_uniformity_failure_keeps_model_test_but_withholds_formal_checkpoint():
    source = SCRIPT.read_text(encoding="utf-8")
    controller = CONTROLLER.read_text(encoding="utf-8")

    # Artifact completeness and scientific uniformity are separate gates.
    assert 'physical_feature_uniformity_manifest.json" overall_status PASS' in source
    assert 'json_contract "$UNIFORMITY/physical_feature_uniformity_summary.json" overall_status PASS' not in source
    assert 'uniform_pass=uniform.get("overall_status")=="PASS"' in source
    assert '"PROVISIONAL_UNIFORMITY_FAIL" if model_pass else "FAIL"' in source

    # Every 100k checkpoint records a completed model suite even when the
    # distribution is provisional; only strict uniformity creates formal PASS.
    model_marker = source.index('touch "$MODEL_MARKER"')
    uniformity_branch = source.index('if [[ "$UNIFORM_STATUS" == "PASS" ]]')
    formal_marker = source.index('touch "$FORMAL_MARKER"')
    assert model_marker < uniformity_branch < formal_marker
    assert '--allow-provisional-uniformity' in controller
    assert '--no-fail-exit' in controller


def test_checkpoint_runner_records_strict_tandem_ood_evidence():
    source = SCRIPT.read_text(encoding="utf-8")
    required_fragments = (
        "train_physical_feature_tandem_inverse.py",
        "audit_tandem_predicted_geometry_feasibility.py",
        "compare_tandem_geometry_anchor_ablation.py",
        "select_balanced_mse_bni_temperature.py",
        "compare_balanced_mse_bni_ablation.py",
        "audit_physical_cell_model_tail_error.py",
        "audit_physical_feature_input_ablation_readiness.py",
        "audit_transformer_ground_ring_spacing.py",
        "compare_physical_feature_q_input_ablation.py",
        "audit_broadband_sparameter_surrogate_readiness.py",
        "audit_physical_feature_extraction_frequency_stability.py",
        "audit_geometry_response_effective_dimension.py",
        "benchmark_frequency_domain_self_transfer.py",
        "benchmark_frequency_sequence_architectures.py",
        "benchmark_cross_frequency_resolution.py",
        "audit_inverse_one_to_many_geometry_multiplicity.py",
        "audit_physical_feature_conformal_calibration.py",
        "compare_global_vs_mondrian_conformal_calibration.py",
        "audit_low_frequency_coupled_rl_consistency.py",
        "plan_tandem_local_refinement_benchmark.py",
        "audit_physical_feature_boundary_ood_stress.py",
        "train_broadband_sparameter_pca_surrogate.py",
        "train_broadband_qmin_physical_spec_baseline_at_200k",
        "train_broadband_qp_qs_physical_spec_baseline_at_200k",
        '--q-broadband-summary "$BROADBAND_QMIN_EXPANDER/broadband_sparameter_pca_surrogate_summary.json"',
        '--qp-qs-broadband-summary "$BROADBAND_QP_QS_EXPANDER/broadband_sparameter_pca_surrogate_summary.json"',
        "--predictor-role physical_spec --expected-predictor-count 5",
        'expected="WAITING_FOR_200K" if index==1 else "PASS"',
        "--split-mode physical_cell_grouped",
        "--resume-completed-candidates",
        "--physical-cell-lower 0.5,0.5,5,0",
        "--physical-cell-upper 3,3,25,0.8",
        "--min-four-d-entropy-frac 0.80 --max-four-d-bin-imbalance 4.0",
        'physical_feature_uniformity_manifest.json" overall_status PASS',
        'physical_feature_inverse_checkpoint_test_summary.json" execution_status PASS',
        'physical_feature_inverse_checkpoint_test_summary.json" eligible_for_model_success_claim False',
        '"four_d_normalized_entropy"',
        '"four_d_nonzero_bin_imbalance"',
        '--split-seed "$SPLIT_SEED"',
        '--model-seed) MODEL_SEED="$2"',
        '"cross_checkpoint_split_seed":int(split_seed)',
        '"tandem_ood_status"',
        '"physical_cell_tail_error_status"',
        '"physical_cell_tail_error_row_weighted_rmse"',
        '"physical_cell_tail_error_equal_cell_rmse"',
        '"physical_cell_tail_error_p95_rmse"',
        '"physical_cell_tail_error_max_rmse"',
        '"physical_cell_tail_error_worst_to_median_ratio"',
        '"physical_cell_tail_error_contract_fingerprint"',
        '"physical_cell_tail_error_boundary"',
        '"uniformity_artifact_manifest_status"',
        '"uniformity_visual_artifacts"',
        '"model_report_figure_artifacts"',
        '"tandem_topology_feasibility_weight"',
        '"tandem_topology_feasibility_is_label_free"',
        '"tandem_predicted_geometry_feasibility_status"',
        '"tandem_predicted_geometry_valid_fraction"',
        '"tandem_geometry_anchor_ablation_status"',
        '"tandem_geometry_anchor_ablation_decision"',
        '"tandem_response_only_relative_improvement"',
        '"tandem_response_only_improvement_ci_lower"',
        '"tandem_response_only_improvement_ci_upper"',
        '"tandem_response_only_cell_balanced_improvement_ci_lower"',
        '"tandem_response_only_cell_balanced_improvement_ci_upper"',
        '"tandem_anchor_ablation_bootstrap_status"',
        '"tandem_anchor_ablation_bootstrap_fingerprint"',
        '"ground_ring_spacing_audit_status"',
        '"ground_ring_spacing_audit_decision"',
        '"ground_ring_spacing_below_advisory_fraction"',
        '"ground_ring_spacing_boundary"',
        '"tandem_ood_split_audit"',
        '"tandem_evaluation_isolation"',
        '"tandem_model_comparison_contract"',
        'tandem_isolation.get("overall_status")=="PASS"',
        'tandem_isolation.get("test_set_used_for_gradient_updates") is False',
        'tandem_isolation.get("test_set_used_for_early_stopping") is False',
        'tandem_isolation.get("test_set_used_for_model_or_hyperparameter_selection") is False',
        'tandem_isolation.get("test_set_used_for_acceptance_threshold_tuning") is False',
        'tandem_isolation.get("test_set_used_only_for_post_training_evaluation") is True',
        'is_sha256(tandem_model_contract.get("fingerprint_sha256"))',
        'len(tandem_model_contract.get("geometry_columns") or [])==10',
        '"direct_tandem_shared_split_fingerprint"',
        '"input_ablation_readiness_status"',
        '"q_input_ablation_status"',
        '"broadband_sparameter_readiness_status"',
        '"broadband_baseline_status"',
        '"broadband_baseline_raw_input_s4p_quality"',
        '"physical_feature_frequency_stability_status"',
        '"geometry_response_effective_dimension_status"',
        '"geometry_effective_dimension_90pct"',
        '"frequency_self_transfer_status"',
        '"frequency_self_transfer_decision"',
        '"frequency_self_transfer_test_full_band_relative_improvement"',
        '"frequency_self_transfer_test_target_relative_improvement"',
        '"frequency_self_transfer_test_frequency_regression_fraction"',
        '"frequency_domain_self_transfer":record(frequency_self_transfer_raw)',
        '"frequency_sequence_architecture_status"',
        '"frequency_sequence_architecture_decision"',
        '"frequency_sequence_architecture_test_full_band_relative_improvement"',
        '"frequency_sequence_architecture_test_target_relative_improvement"',
        '"frequency_sequence_architecture_test_resonance_relative_improvement"',
        '"frequency_sequence_architecture_test_frequency_regression_fraction"',
        '"frequency_sequence_architecture_parameter_count_ratio"',
        '"frequency_sequence_architecture_benchmark":record(frequency_sequence_raw)',
        '"cross_frequency_resolution_status"',
        '"cross_frequency_resolution_decision"',
        '"cross_frequency_resolution_test_held_out_relative_degradation"',
        '"cross_frequency_resolution_test_held_out_regression_fraction"',
        '"cross_frequency_resolution_is_neural_operator"',
        '"cross_frequency_resolution":record(frequency_resolution_raw)',
        '"inverse_geometry_multiplicity_status"',
        '"inverse_geometry_multiplicity_recommendation"',
        '"inverse_geometry_multiplicity_evidence_stage"',
        '"inverse_geometry_multiplicity_top_k_eligible"',
        '"physical_feature_conformal_calibration_status"',
        '"physical_feature_conformal_boundary"',
        '"physical_feature_mondrian_conformal_status"',
        '"physical_feature_mondrian_conformal_decision"',
        '"physical_feature_mondrian_conformal_recommendation"',
        '"physical_feature_mondrian_supported_cell_fraction"',
        '"physical_feature_mondrian_supported_row_fraction"',
        '"physical_feature_mondrian_conformal_comparison":record(mondrian_conformal_raw)',
        '"low_frequency_coupled_rl_consistency_status"',
        '"low_frequency_coupled_rl_boundary"',
        '"tandem_local_refinement_plan_status"',
        '"tandem_local_refinement_boundary"',
        '"physical_feature_boundary_ood_stress_status"',
        '"physical_feature_boundary_ood_stress_boundary"',
        '"physical_spec_spectral_expander_status"',
        '"physical_spec_spectral_expander_test_complex_rmse"',
        '"physical_spec_spectral_expander_target_frequency_ghz"',
        '"physical_spec_spectral_expander_target_complex_rmse"',
        '"physical_spec_spectral_expander_raw_input_s4p_quality"',
        '"q_input_ablation_target_frequency_relative_improvement"',
        '--target-frequency-ghz 15',
        '--max-input-reciprocity-error 0.02 --max-input-passivity-excess 0.05',
        'raw_s4p_quality_pass(broadband_baseline)',
        'raw_s4p_quality_pass(physical_spec_spectral_expander)',
        '"physical_spec_spectral_expander_boundary"',
        "--low-frequency-ghz 5 --current-frequency-ghz 15 --forward-step-ghz 0.5",
        "audit_geometry_response_effective_dimension_at_300k",
        "benchmark_frequency_domain_self_transfer_at_300k",
        "benchmark_frequency_sequence_architectures_at_300k",
        "benchmark_cross_frequency_resolution_at_300k",
        "--sparse-frequency-stride 2",
        "--optimizer-updates 512",
        "equal_budget_contract.equal_optimizer_updates True",
        "checks.sparse_training_excludes_all_held_out_frequencies True",
            "checks.raw_input_reciprocity_threshold_pass True",
            "checks.raw_input_passivity_threshold_pass True",
            "checks.frequency_bands_are_monotonic_contiguous True",
            "checks.same_initial_weights_per_band True",
            "checks.physical_metric_extraction_available True",
            "equal_budget_contract.test_set_used_for_training False",
            "equal_budget_contract.test_set_used_for_checkpoint_selection False",
        '"WAITING_FOR_300K" if index<3 else "NOT_REPEATED_AFTER_300K"',
        '"WAITING_FOR_300K" if index<3 else "NOT_REPEATED_AFTER_300K"',
        '"RUN_EQUAL_BUDGET_MLP_VS_GRU_AT_300K" if index<3 else "USE_RECORDED_300K_SEQUENCE_ARCHITECTURE_EVIDENCE"',
        "checks.equal_optimizer_updates_per_seed True",
        "checks.parameter_budget_ratio_within_limit True",
        "checks.full_frequency_sequence_used True",
        "equal_budget_contract.test_set_used_for_selection False",
        "audit_inverse_one_to_many_geometry_multiplicity_at_500k",
        "audit_inverse_one_to_many_geometry_multiplicity_at_100k_coarse",
        '--evidence-stage "$MULTIPLICITY_STAGE"',
        '"COARSE_100K_COMPLETE_FINE_WAITING_FOR_500K" if index<5 else "NOT_REPEATED_AFTER_500K"',
        "audit_physical_feature_conformal_calibration_at_600k",
        "compare_global_vs_mondrian_conformal_calibration_at_600k",
        '"WAITING_FOR_600K" if index<6 else "NOT_REPEATED_AFTER_600K"',
        "audit_low_frequency_coupled_rl_consistency_at_700k",
        '"WAITING_FOR_700K" if index<7 else "NOT_REPEATED_AFTER_700K"',
        "plan_tandem_local_refinement_benchmark_at_800k",
        '"WAITING_FOR_800K" if index<8 else "NOT_REPEATED_AFTER_800K"',
        "audit_physical_feature_boundary_ood_stress_at_900k",
        '"WAITING_FOR_900K" if index<9 else "NOT_REPEATED_AFTER_900K"',
        "train_physical_spec_to_broadband_s4p_baseline_at_checkpoint",
        "--predictor-role physical_spec --expected-predictor-count 4",
        'physical_spec_spectral_expander.get("overall_status")=="COMPLETE_REVIEW_REQUIRED"',
        '--max-prediction-rows "$TANDEM_MAX_PREDICTION_ROWS"',
        'TANDEM_MAX_PREDICTION_ROWS="$CHECKPOINT_COUNT"',
        "audit_physical_cell_model_tail_error",
        "physical_cell_model_tail_error_summary.json",
        "--minimum-test-rows 1000 --minimum-test-cells 8",
        'physical_cell_tail.get("overall_status")=="PASS"',
        'uniform_manifest.get("overall_status")=="PASS"',
        'ridge.get("execution_status")=="PASS"',
        'ridge.get("eligible_for_model_success_claim") is False',
        "report_figures_complete",
        '"uniformity_artifact_manifest":record(uniform_manifest_raw)',
        '"physical_cell_model_tail_error":record(physical_cell_tail_raw)',
        "--split-reference-columns input__lp_nh_center,input__ls_nh_center,input__q_center,input__k_abs_center",
        "--response-loss-scaling declared_range",
        '--topology-feasibility-weight "$TOPOLOGY_FEASIBILITY_WEIGHT"',
        "--response-weight-schedule warmup_ramp_adaptive_ema",
        "train_tandem_response_only_physical_cell_ood_at_100k",
        "--geometry-anchor-weight 0",
        "--response-warmup-fraction 0 --response-ramp-fraction 0.20",
        "--require-paired-bootstrap --bootstrap-replicates 2000 --bootstrap-confidence 0.95",
        "--minimum-paired-test-rows 1000 --minimum-paired-test-cells 8",
        "paired_cluster_bootstrap.status PASS",
        "decision_rule paired_cluster_bootstrap_row_and_cell_balanced_ci_lower_ge_material_improvement",
        'anchor_ablation.get("decision_rule")=="paired_cluster_bootstrap_row_and_cell_balanced_ci_lower_ge_material_improvement"',
        '(anchor_ablation.get("paired_cluster_bootstrap") or {}).get("status")=="PASS"',
        "select_balanced_mse_bni_temperature_at_200k",
        "train_balanced_mse_bni_same_budget_at_200k",
        "compare_mse_vs_balanced_mse_bni_at_200k",
        "--response-loss-family balanced_mse_bni --balanced-mse-temperature",
        "row_equal_cell_and_p90_tail_cluster_bootstrap_ci_lower_ge_material_improvement",
        'bni_ablation.get("overall_status")=="PASS"',
        '"balanced_mse_bni_ablation_status"',
        '"balanced_mse_bni_p90_tail_improvement_ci_lower"',
        '"balanced_mse_bni_ablation":record(bni_ablation_raw)',
        "--recommended-margin-to-diameter-ratio 0.3333333333333333",
        "--recover-margin-from-evaluation-metadata",
        "--max-row-artifact 20000",
        'artifacts.ratio_histogram_status PASS',
        'artifacts.response_scatter_status PASS',
        '"ground_ring_spacing_audit":record(ground_ring_spacing_raw)',
        '"declared_range_balanced_loss"',
        '"adaptive_picc_schedule"',
        '"label_free_topology_feasibility"',
        '"topology_feasibility_enabled"',
        '"topology_feasibility_columns_available"',
        '"tandem_physical_cell_ood"',
        '"tandem_predicted_geometry_feasibility"',
        '--config "$GEOMETRY_CONFIG" --out-dir "$TANDEM_FEASIBILITY"',
        'tandem_feasibility.get("overall_status")=="PASS"',
        '--local-refinement-steps "$LOCAL_REFINEMENT_STEPS"',
        '--local-refinement-starts "$LOCAL_REFINEMENT_STARTS"',
        '--local-refinement-learning-rate "$LOCAL_REFINEMENT_LEARNING_RATE"',
        '--local-refinement-jitter "$LOCAL_REFINEMENT_JITTER"',
        "COMPLETE_REVIEW_REQUIRED",
    )
    assert all(fragment in source for fragment in required_fragments)
    assert source.count("--max-input-reciprocity-error 0.02 --max-input-passivity-excess 0.05") == 7
    assert source.count('--topology-feasibility-weight "$TOPOLOGY_FEASIBILITY_WEIGHT"') == 4
    assert source.count('--local-refinement-steps "$LOCAL_REFINEMENT_STEPS"') == 4
    assert source.count('--local-refinement-starts "$LOCAL_REFINEMENT_STARTS"') == 4
