"""New last2 integration only; every candidate/physical-looking byte is synthetic.

The accepted126 table is a synthetic fixture, not generated by replaying the old
consumer. Actual run/validate_export/consume/feature/summary functions execute
only for newly supplied synthetic126/127 chains. Opaque acceptance SHAs alone
are monkeypatched to these fixtures. No real data/model/native tests are run.
"""
from collections import Counter
from copy import deepcopy
import csv
import json
from pathlib import Path
import socket
import subprocess

import pytest

from research.broadband56_nn import eucap15_development128_last2 as m
from research.broadband56_nn.frequency_physical_statistics import csv_write
from tests.fixtures.eucap15_development128_incremental_fixture import IncrementalFixture


def save(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('x') as stream:
        json.dump(value, stream, sort_keys=True, allow_nan=False)
        stream.write('\n')
    return m.pin(path)


@pytest.fixture(autouse=True)
def no_real_execution(monkeypatch):
    def forbidden(*a, **k):
        raise AssertionError('No processes, networking, model or dataset read')
    monkeypatch.setattr(subprocess, 'Popen', forbidden)
    monkeypatch.setattr(subprocess, 'run', forbidden)
    monkeypatch.setattr(socket, 'socket', forbidden)
    original = Path.open
    def guarded(path, *args, **kwargs):
        if path.suffix in ('.pt', '.npz') or path.name.startswith('UNREAD_'):
            forbidden()
        return original(path, *args, **kwargs)
    monkeypatch.setattr(Path, 'open', guarded)


def fixture(tmp_path, monkeypatch, new=(126, 127)):
    f = IncrementalFixture(tmp_path/'fixture', monkeypatch)
    previous = deepcopy(f.context().rows)
    states = ['ANALYTIC_FAIL']*35 + ['GDS_FAIL']*6 + ['EMX_INVALID']*37 + ['STRICT_VALID']*48 + ['PENDING']*2
    for i, (row, state) in enumerate(zip(previous, states)):
        row['state'] = state
        if i < 126:
            if f.snapshot['requests'][i]['result'] is None:
                f.snapshot['requests'][i]['result'] = f.publish(row['request_id']+'/RESULT.json',
                    dict(SYNTHETIC_ACCEPTED_BASELINE_ONLY=True, request_id=row['request_id']))
            row['native_result_pin'] = f.snapshot['requests'][i]['result']
        else:
            row['native_result_pin'] = None
        if state == 'STRICT_VALID':
            row['actual'] = [1., 1., 10., .3 if i < 118 else .4]
            row['strict_joint_hit'] = i < 118
            row['touchstone_sha'] = 'b'*64
    for i in new:
        f.chain(i, 'success')
    # The older fixture's flat mirror does not represent separate candidate
    # roots. Relocate only synthetic bytes to explicit per-candidate roots.
    ids = {r['request_id'] for r in previous}
    for original, entry in f.entries.items():
        path = Path(original)
        if path.is_relative_to(f.native):
            relative = path.relative_to(f.native)
            if relative.parts[0] in ids:
                local = f.root/'candidate_mirror'/relative
                local.parent.mkdir(parents=True, exist_ok=True)
                with local.open('xb') as stream:
                    stream.write(Path(entry['resolved']['path']).read_bytes())
                entry['resolved'] = m.pin(local)
    f.seal_snapshot()
    baseline = tmp_path/'accepted_synthetic126'
    baseline.mkdir()
    csv_write(baseline/'REQUEST_RESULTS.csv', previous, fields=m.CSV_FIELDS)
    summary = save(baseline/'SUMMARY.json', dict(N_original_requests=128,
        N_owner_terminal_receipts_consumed=126, N_joint_hit=40,
        model_id=m.initial.MODEL_ID, FINAL=False))
    intent = save(baseline/'INTENT.json', dict(manifest=f.manifest_pin, qa=f.qa_pin))
    native_sources = [deepcopy(f.entries[r['native_result_pin']['path']])
                      for r in previous if r['native_result_pin'] is not None]
    closure = save(baseline/'SOURCE_CLOSURE.json', dict(native_sources=native_sources))
    receipt = save(baseline/'RECEIPT.json', dict(
        schema='eucap15_development128_result_receipt.v1',
        status='PASS_PUBLISHED_SNAPSHOT_ACCOUNTING_NOT_FINAL', N_original_requests=128,
        FINAL=False, artifacts=[m.pin(baseline/'REQUEST_RESULTS.csv'), summary, intent, closure],
        implementation=[m.pin(Path(m.existing.__file__))]))
    qa = save(baseline/'QA_RECEIPT.json', dict(
        schema='independent_development128_statistics_qa.v1',
        status='GO_SCOPED_DESCRIPTIVE_DEVELOPMENT128', source_result_receipt=receipt,
        FINAL=False, N_terminal=126, N_joint_hit=40))
    monkeypatch.setattr(m, 'BASE_RECEIPT_SHA', receipt['sha256'])
    monkeypatch.setattr(m, 'BASE_QA_SHA', qa['sha256'])
    f.previous, f.base_receipt, f.base_qa = previous, receipt, qa
    f.old_resolved_roots = {Path(e['resolved']['path']).parent for e in native_sources}
    return f


def closed_snapshot(f, new=(126, 127), *, mutation=None):
    """Synthetic byte-pinned full owner/preview/closing publication; no exporter."""
    export = f.root/'new_synthetic_closed_export'
    export.mkdir()
    snapshot = deepcopy(f.snapshot)
    owner = deepcopy(f.owner)
    owner.update(status='BYTE_COPY_ONLY_REQUIRES_CLOSED_EXPORT_RECEIPT',
        previous_export={'synthetic': True}, old_results_recopied=0,
        new_results_copied=len(new))
    owner_pin = save(export/'EXPORT_RECEIPT.json', owner)
    snapshot['owner_export'] = owner_pin
    snapshot['sources'].append(dict(original=owner_pin, resolved=owner_pin))
    if mutation:
        mutation(snapshot)
    preview = save(export/'READER_SNAPSHOT.json', snapshot)
    close = save(export/'CLOSED_EXPORT_RECEIPT.json', dict(
        schema='eucap15_development128_closed_local_delta.v1',
        status='PASS_CLOSED_BYTE_EXPORT_NOT_ACCEPTED', export=owner_pin,
        N_original_requests=128, N_original_analytic_failures=35,
        old_results_recopied=0, source_bytes_unchanged_at_final_check=True,
        actual_emx_execution_in_this_export=False, native_calls=0, ssh_calls=0,
        process_queries=0, FINAL=False, snapshot=preview,
        new_terminal_ids=[f.items[i]['request_id'] for i in new], new_results_copied=len(new)))
    snapshot['closed_delta'] = close
    snapshot['sources'] += [dict(original=p, resolved=p) for p in (close, preview)]
    return snapshot


def deny_old_physical_opens(f, monkeypatch):
    real_open = Path.open
    touched = []
    def guarded(path, *args, **kwargs):
        if any(path.is_relative_to(root) for root in f.old_resolved_roots):
            touched.append(str(path))
            raise AssertionError('Attempted old126 physical candidate read')
        return real_open(path, *args, **kwargs)
    monkeypatch.setattr(Path, 'open', guarded)
    return touched


@pytest.mark.parametrize('new', [(126,), (126, 127)])
def test_run_delta_unmocked_full_closure_and_only_new_physical_chains(tmp_path, monkeypatch, new):
    f = fixture(tmp_path, monkeypatch, new)
    snapshot = closed_snapshot(f, new)
    snapshot_pin = save(f.root/'EXTERNAL_SNAPSHOT.json', snapshot)
    touched = deny_old_physical_opens(f, monkeypatch)
    output = tmp_path/'last2_result'
    result = m.run(Path(f.base_receipt['path']), Path(f.base_qa['path']), output,
        snapshot_path=Path(snapshot_pin['path']), snapshot_sha256=snapshot_pin['sha256'])
    merged = m.parse_rows((output/'REQUEST_RESULTS.csv').read_bytes())
    assert merged[:126] == f.previous[:126]
    assert len(merged) == 128 and result['N_original_requests'] == 128
    assert result['new_terminal_results_consumed'] == len(new)
    assert result['N_owner_terminal_receipts_consumed'] == 126 + len(new)
    assert result['N_joint_hit'] == 40 + len(new)
    assert result['N_strict_valid'] == 48 + len(new)
    assert result['N_pending_requests'] == 2 - len(new)
    assert Counter(r['state'] for r in merged)['ANALYTIC_FAIL'] == 35
    assert all(merged[i]['actual'] == [1., 1., 10., .3] for i in new)
    assert all(merged[i]['q_proxy'] == f.previous[i]['q_proxy'] and merged[i]['q_emx'] is None for i in new)
    assert touched == [] and result['FINAL'] is False
    saved = json.loads((output/'RECEIPT.json').read_text())
    assert f.base_receipt in saved['source_pins'] and f.base_qa in saved['source_pins']
    for line in (output/'SHA256SUMS').read_text().splitlines():
        digest, name = line.split('  ', 1)
        assert m.pin(output/name)['sha256'] == digest


@pytest.mark.parametrize('attack', ['missing_closed_receipt', 'changed_old_result_in_external'])
def test_run_full_owner_closure_rejection_cannot_be_hidden_by_sparse_view(tmp_path, monkeypatch, attack):
    f = fixture(tmp_path, monkeypatch)
    snapshot = closed_snapshot(f)
    if attack == 'missing_closed_receipt':
        del snapshot['closed_delta']
    else:
        snapshot['requests'][40]['result']['sha256'] = 'a'*64
    p = save(f.root/'BROKEN_EXTERNAL_SNAPSHOT.json', snapshot)
    touched = deny_old_physical_opens(f, monkeypatch)
    out = tmp_path/'no_go'
    with pytest.raises(ValueError):
        m.run(Path(f.base_receipt['path']), Path(f.base_qa['path']), out,
            snapshot_path=Path(p['path']), snapshot_sha256=p['sha256'])
    assert (out/'FAILURE_RECEIPT.json').exists()
    assert not (out/'REQUEST_RESULTS.csv').exists() and touched == []


def test_new_original_alias_to_old_resolved_tree_rejected_before_open(tmp_path, monkeypatch):
    f = fixture(tmp_path, monkeypatch)
    # An old existing result is pointed at a new apparent safe location in the
    # snapshot. Trusted old roots must still come from accepted SOURCE_CLOSURE.
    old = f.previous[40]['native_result_pin']
    trusted_old = f.entries[old['path']]['resolved']
    fake_safe = f.root/'pretended_safe_old_copy.json'
    with fake_safe.open('xb') as stream:
        stream.write(Path(trusted_old['path']).read_bytes())
    # A new owner-export reference aliases those actual old bytes. Its content
    # need not be a valid export: correct isolation rejects before opening it.
    alias = dict(trusted_old, path=str(f.root/'new_owner_alias.json'))
    def mutate(snapshot):
        for entry in snapshot['sources']:
            if entry['original']['path'] == old['path']:
                entry['resolved'] = m.pin(fake_safe)
        snapshot['owner_export'] = alias
        snapshot['sources'].append(dict(original=alias, resolved=trusted_old))
    snapshot = closed_snapshot(f, mutation=mutate)
    p = save(f.root/'ALIASED_EXTERNAL_SNAPSHOT.json', snapshot)
    touched = deny_old_physical_opens(f, monkeypatch)
    out = tmp_path/'alias_no_go'
    with pytest.raises(ValueError, match='accepted candidate'):
        m.run(Path(f.base_receipt['path']), Path(f.base_qa['path']), out,
            snapshot_path=Path(p['path']), snapshot_sha256=p['sha256'])
    assert touched == [] and not (out/'REQUEST_RESULTS.csv').exists()
