#!/usr/bin/env python3
"""Generate a grouped Markdown catalog for every command-line script."""

from __future__ import annotations

import ast
from collections import defaultdict
from pathlib import Path


CATEGORIES = (
    ("Auditing and quality gates", ("audit_", "verify_", "validate_")),
    ("Dataset and artifact construction", ("build_", "backfill_", "enrich_", "derive_")),
    ("Training and prediction", ("train_", "predict_")),
    ("Comparison and benchmarking", ("compare_", "benchmark_", "evaluate_", "aggregate_")),
    ("Planning and selection", ("plan_", "select_", "recommend_", "stratify_")),
    ("Campaign execution", ("run_", "watch_", "monitor_", "supervise_")),
    ("Import, export, and packaging", ("import_", "export_", "package_", "prepare_")),
    ("Diagnosis and discovery", ("diagnose_", "discover_", "scan_", "estimate_")),
    ("Queue and accepted-pool operations", ("materialize_", "merge_", "stage_", "patch_")),
    ("Plotting and reporting", ("plot_", "render_", "summarize_")),
)


def description(path: Path) -> str:
    if path.suffix == ".py":
        try:
            value = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
        except (OSError, SyntaxError, UnicodeDecodeError):
            value = None
        if value:
            return value.strip().splitlines()[0]
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            text = line.strip().removeprefix("#").strip()
            if text and not text.startswith("!"):
                return text
    except (OSError, UnicodeDecodeError):
        pass
    return "No module description available."


def category(name: str) -> str:
    for title, prefixes in CATEGORIES:
        if name.startswith(prefixes):
            return title
    return "Other utilities"


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    grouped: dict[str, list[Path]] = defaultdict(list)
    for path in sorted((root / "scripts").iterdir()):
        if path.is_file() and path.suffix in {".py", ".sh"}:
            grouped[category(path.stem)].append(path)
    site_scripts = sorted(
        path
        for path in (root / "site_ops").rglob("*")
        if path.is_file() and path.suffix in {".py", ".sh", ".ps1"}
    )
    lines = [
        "# Script Catalog",
        "",
        "Generated by `tools/build_script_catalog.py`. Every executable research script is listed once.",
        "",
        f"Total scripts: **{sum(len(items) for items in grouped.values())}**.",
        "",
    ]
    order = [title for title, _prefixes in CATEGORIES] + ["Other utilities"]
    for title in order:
        items = grouped.get(title, [])
        if not items:
            continue
        lines.extend([f"## {title}", ""])
        for path in items:
            relative = path.relative_to(root).as_posix()
            lines.append(f"- [`{relative}`](../{relative}) - {description(path)}")
        lines.append("")
    lines.extend(
        [
            "## Sanitized site-operation archive",
            "",
            "These historical wrappers require site review and are not portable defaults.",
            "",
        ]
    )
    for path in site_scripts:
        relative = path.relative_to(root).as_posix()
        lines.append(f"- [`{relative}`](../{relative}) - {description(path)}")
    lines.extend(["", f"Archived site-operation scripts: **{len(site_scripts)}**.", ""])
    target = root / "docs" / "SCRIPT_CATALOG.md"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
